# Generated by Django 4.0.6 on 2022-07-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=30)),
                ('segundoNome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
