# Generated by Django 4.0.6 on 2022-07-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_primeironome_cliente_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_produto', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('unidade', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nome',
            new_name='nome',
        ),
    ]
