# Generated by Django 4.0.6 on 2022-07-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='unidade',
            new_name='quantidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_unidade',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
