# Generated by Django 4.0.6 on 2022-07-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_unidade_produto_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_do_pedido',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
