# Generated by Django 4.0.6 on 2022-07-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pedido_valor_do_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valor_do_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ManyToManyField(to='api.produto'),
        ),
    ]
