# Generated by Django 4.0.6 on 2022-07-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_pedido_valor_do_pedido_remove_pedido_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='concluido',
            field=models.CharField(default='não', max_length=30),
            preserve_default=False,
        ),
    ]
