# Generated by Django 4.0.6 on 2022-07-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pedido_concluido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='concluido',
            new_name='pedido_concluido',
        ),
    ]
