# Generated by Django 4.0.6 on 2022-07-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_faturamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='faturamento_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
