# Generated by Django 4.0.6 on 2022-07-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_faturamento_faturamento_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturamento',
            name='faturamento_total',
        ),
    ]
