# Generated by Django 4.0.6 on 2022-07-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_faturamento_faturamento_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='pedido',
            field=models.ManyToManyField(to='api.pedido'),
        ),
    ]
