# Generated by Django 4.0.6 on 2022-07-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_faturamento_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='lucro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='faturamento',
            name='pedido',
        ),
    ]
